name: Condition workflow
on: push
jobs:
  skip-or-run:
    if: ${{ github.actor == "keishotbow" }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${ACTOR}"
        env: 
          ACTOR: ${{ github.actor }}
